os: linux
dist: bionic
language: go

env:
    global:
      - TEST_DB_USERNAME=postgres
      - TEST_DB_PASSWORD=postgres
      - TEST_DB_NAME=test_services

branches:
  only:
  - staging
  - master

stages:
  - build_current
  - build_tip

jobs:
  allow_failures:
    - go: tip
  fast_finish: true
  include:
  - stage: "build_current"
    go: master
    services:
    - postgresql
    before_script:
    - sudo -u postgres psql -U postgres -d postgres -c "alter user postgres with password 'postgres';"
    - sudo -u postgres psql -U postgres -d postgres -c "create database test_services;"
    script:
    - go test -v
    - go build -v

notifications:
  email: false
  slack:
    secure: "n51gASHYQdtQwHItHatA8IXW2JjCcjKgSPxQBzh0VvtEGtbB1qrzmbt07bMJ0Cd9pXHU6iatzSMMeypFi9Z/06c4fikoxpHJ0u2Re4qJ93DRHIgev+WFhy+5RqeHrykdn7N+WOutWju2ButgWt03gvNxC503Mayjq2LetmGlUzNd94V6wxktUiV+7OEGvpw4//FX6tsfluilWwAKabMPxaWhMagtFfzr0av87xd4qXJQMrtcK6HYtoM9nh6RfloQA5BLgrvz3KmkcCi302auIJcBw1ENd5Rv7NP2J4NCn8Mj6lYsKXVCNeeuHpSD73VdhNZneSE+Af75kq3WbX+VE2vlpfgJTm1NZMy8KDQ6mH5OUSDcEo6J5Exuy2JXnZUEPoK8tbrqa9CXTnlzRHuH/twnrxMZUYcOCMa0EofM2KU4iedTgtrzZkBNbv6RJ6HYc4rQtEHdogxCPiECyuGBHc47gZazASkbYPZQ3UkCSO1dI1Uv/K3dGTG9yd3Gr6ZYP3KOekRcaYrDWUbMyGXEaC/MYjX/dpXj/1iIP/Wxd5mMuXGgtuTQkfvE85mdTI+RUQdpSpQHgW4bQQU8fkxVjh/RW2xw3pF3oG/5fIYxU7FNGfJcUcFdSxbWvR1UtzuMYSePaorTYoypeLKlOv/X24duSFY4DyAU8KDXEO/aBjc="
